version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: habit-tracker-app
    working_dir: /app
    volumes:
      - ./:/app
      - composer-cache:/tmp/composer
    env_file:
      - .env
      - .env.local
    environment:
      APP_ENV: ${APP_ENV:-dev}
    depends_on:
      - db
      - redis
    ports:
      - "8000:8000"
    command: ["php", "-S", "0.0.0.0:8000", "-t", "public"]

  db:
    image: postgres:16
    container_name: habit-tracker-db
    env_file:
      - .env
      - .env.local
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-symfony}
      POSTGRES_USER: ${POSTGRES_USER:-symfony}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-symfony}
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:7
    container_name: habit-tracker-redis
    ports:
      - "6379:6379"

volumes:
  pgdata:
  composer-cache:
