version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: habit-tracker-app
    working_dir: /app
    volumes:
      - ./:/app
      - composer-cache:/tmp/composer
    environment:
      APP_ENV: dev
      # Symfony reads env vars over .env files; adjust as needed
      DATABASE_URL: "postgresql://symfony:symfony@db:5432/symfony?serverVersion=16&charset=utf8"
      REDIS_URL: "redis://redis:6379"
    depends_on:
      - db
      - redis
    ports:
      - "8000:8000"
    command: ["php", "-S", "0.0.0.0:8000", "-t", "public"]

  db:
    image: postgres:16
    container_name: habit-tracker-db
    environment:
      POSTGRES_DB: symfony
      POSTGRES_USER: symfony
      POSTGRES_PASSWORD: symfony
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:7
    container_name: habit-tracker-redis
    ports:
      - "6379:6379"

volumes:
  pgdata:
  composer-cache:
